"use client"

import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "Mess Master",
    "welcome": "Welcome to Mess Master",
    "login": "Login",
    "signup": "Sign Up",
    "dashboard": "Dashboard",
    "overview": "Overview",
    "meals": "Meals",
    "finance": "Finance",
    "members": "Members",
    "updates": "Updates",
    "settings": "Settings",
    "logout": "Logout",
    "profile": "Profile",
    "add_meal": "Add Meal",
    "add_cost": "Add Cost",
    "add_deposit": "Add Deposit",
    "add_member": "Add Member",
    "management": "Management",
    "main_menu": "Main Menu",
    "email": "Email",
    "password": "Password",
    "full_name": "Full Name",
    "phone": "Phone",
    "create_account": "Create Account",
    "already_have_account": "Already have an account?",
    "dont_have_account": "Don't have an account?",
    "login_to_account": "Login to your account",
    "forgot_password": "Forgot Password?",
    "reset_password": "Reset Password",
    "total_meals": "Total Meals",
    "meal_rate": "Meal Rate",
    "total_cost": "Total Cost",
    "balance": "Balance",
    "recent_activity": "Recent Activity",
    "no_activity": "No recent activity",
    "mess_manager": "Mess Manager",
    "role": "Role",
    "status": "Status",
    "actions": "Actions",
    "remove": "Remove",
    "edit": "Edit",
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "confirm": "Confirm",
    "search": "Search...",
    "join_mess": "Join Mess",
    "create_mess": "Create Mess",
    "mess_code": "Mess Code",
    "my_profile": "My Profile",
    "change_password": "Change Password",
    "notifications": "Notifications",
    "mark_all_read": "Mark all as read",
    "no_notifications": "No new notifications",
    "active": "Active",
    "inactive": "Inactive",
    "pending": "Pending",
    "rejected": "Rejected",
    "breakfast": "Breakfast",
    "lunch": "Lunch",
    "dinner": "Dinner",
    "date": "Date",
    "amount": "Amount",
    "category": "Category",
    "details": "Details",
    "paid_by": "Paid By",
    "added_by": "Added By",
    "meal_cost": "Meal Cost",
    "other_cost": "Other Cost",
    "shared_cost": "Shared Cost",
    "individual_cost": "Individual Cost",
    "total_deposit": "Total Deposit",
    "member_list": "Member List",
    "invite_member": "Invite Member",
    "start_month": "Start Month",
    "end_month": "End Month",
    "history": "History",
    "system_settings": "System Settings",
    "language": "Language",
    "theme": "Theme",
    "request_sent_to": "Request sent to",
    "no_active_month": "No Active Month Started",
    "ask_manager_start_month": "Ask your manager to start a new month to see stats.",
    "onboarding_subtitle": "To get started, create a new mess or join an existing one.",
    "active_members": "Active Members",
    "search_members": "Search members...",
    "manage_access_transfer": "Manage Access & Transfer",
    "are_you_sure_remove": "Are you sure you want to remove",
    "member_removed": "Member removed",
    "join_mess_to_see_members": "Join a mess to see members.",
    "mess": "Mess",
    "not_set": "Not set",
    "no_mess": "No Mess",
    "join_or_create_mess_to_manage_meals": "Please join or create a mess to manage meals.",
    "no_active_month_manager_start": "No active month found. Ask your manager to start a month.",
    "total_meals_month": "Total Meals (Month)",
    "my_meals": "My Meals",
    "personal_consumption": "Personal Consumption",
    "active_days": "Active Days",
    "days_with_records": "Days with records",
    "no_meal_records_month": "No meal records found for this month.",
    "daily_total": "Daily Total",
    "today": "Today",
    "member": "Member",
    "total_and_actions": "Total & Actions",
    "confirm_delete_deposit": "Are you sure you want to delete this deposit?",
    "deposit_deleted": "Deposit deleted",
    "confirm_delete_expense": "Are you sure you want to delete this expense?",
    "expense_deleted": "Expense deleted",
    "split_with_shoppers": "Split with shoppers",
    "paid_by_shopper_required": "Paid By (Shopper) is required",
    "insufficient_mess_balance": "Insufficient Mess Balance",
    "total_expenses": "Total Expenses",
    "total_deposits": "Total Deposits",
    "expenses": "Expenses",
    "deposits": "Deposits",
    "no_records": "No records found",
    "loading": "Loading...",
    "saving": "Saving...",
    "save_record": "Save Record",
    "save_meal_cost": "Save Meal Cost",
    "save_shared_cost": "Save Shared Cost",
    "save_individual_cost": "Save Individual Cost",
    "confirm_deposit": "Confirm Deposit",
    "start_month_btn": "Start Month",
    "processing": "Processing..."
  },
  bn: {
    "app.name": "মেস মাস্টার",
    "welcome": "মেস মাস্টারে স্বাগতম",
    "login": "লগইন",
    "signup": "সাইন আপ",
    "dashboard": "ড্যাশবোর্ড",
    "overview": "ওভারভিউ",
    "meals": "মীলস",
    "finance": "হিসাব",
    "members": "সদস্যবৃন্দ",
    "updates": "আপডেট",
    "settings": "সেটিংস",
    "logout": "লগআউট",
    "profile": "প্রোফাইল",
    "add_meal": "মিল যোগ করুন",
    "add_cost": "খরচ যোগ করুন",
    "add_deposit": "জমা যোগ করুন",
    "add_member": "সদস্য যোগ করুন",
    "management": "ম্যানেজমেন্ট",
    "main_menu": "মেইন মেনু",
    "email": "ইমেইল",
    "password": "পাসওয়ার্ড",
    "full_name": "পুরো নাম",
    "phone": "ফোন",
    "create_account": "অ্যাকাউন্ট তৈরি করুন",
    "already_have_account": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    "dont_have_account": "কোনো অ্যাকাউন্ট নেই?",
    "login_to_account": "আপনার অ্যাকাউন্টে লগইন করুন",
    "forgot_password": "পাসওয়ার্ড ভুলে গেছেন?",
    "reset_password": "পাসওয়ার্ড রিসেট করুন",
    "total_meals": "মোট মিল",
    "meal_rate": "মিলের রেট",
    "total_cost": "মোট খরচ",
    "balance": "ব্যালেন্স",
    "recent_activity": "সাম্প্রতিক কার্যকলাপ",
    "no_activity": "কোনো সাম্প্রতিক কার্যকলাপ নেই",
    "mess_manager": "মেস ম্যানেজার",
    "role": "রোল",
    "status": "অবস্থা",
    "actions": "অ্যাকশন",
    "remove": "সরান",
    "edit": "এডিট",
    "save": "সংরক্ষণ",
    "cancel": "বাতিল",
    "delete": "মুছুন",
    "confirm": "নিশ্চিত করুন",
    "search": "খুঁজুন...",
    "join_mess": "মেসে যোগ দিন",
    "create_mess": "মেস তৈরি করুন",
    "mess_code": "মেস কোড",
    "my_profile": "আমার প্রোফাইল",
    "change_password": "পাসওয়ার্ড পরিবর্তন",
    "notifications": "নোটিফিকেশন",
    "mark_all_read": "সব পড়া হয়েছে মার্ক করুন",
    "no_notifications": "কোনো নতুন নোটিফিকেশন নেই",
    "active": "সক্রিয়",
    "inactive": "নিষ্ক্রিয়",
    "pending": "অপেক্ষমান",
    "rejected": "বাতিল",
    "breakfast": "সকাল",
    "lunch": "দুপুর",
    "dinner": "রাত",
    "date": "তারিখ",
    "amount": "পরিমাণ",
    "category": "বিভাগ",
    "details": "বিবরণ",
    "paid_by": "পরিশোধ করেছেন",
    "added_by": "যোগ করেছেন",
    "meal_cost": "বাজার খরচ",
    "other_cost": "অন্যান্য খরচ",
    "shared_cost": "শেয়ার্ড খরচ",
    "individual_cost": "ব্যক্তিগত খরচ",
    "total_deposit": "মোট জমা",
    "member_list": "সদস্য তালিকা",
    "invite_member": "সদস্য আমন্ত্রণ",
    "start_month": "মাস শুরু করুন",
    "end_month": "মাস শেষ করুন",
    "history": "ইতিহাস",
    "system_settings": "সিস্টেম সেটিংস",
    "language": "ভাষা",
    "theme": "থিম",
    "request_sent_to": "অনুরোধ পাঠানো হয়েছে",
    "no_active_month": "কোনো সক্রিয় মাস শুরু হয়নি",
    "ask_manager_start_month": "পরিসংখ্যান দেখতে আপনার ম্যানেজারকে নতুন মাস শুরু করতে বলুন।",
    "onboarding_subtitle": "শুরু করতে, একটি নতুন মেস তৈরি করুন বা বিদ্যমান একটিতে যোগদান করুন।",
    "active_members": "সক্রিয় সদস্য",
    "search_members": "সদস্য খুঁজুন...",
    "manage_access_transfer": "অ্যাক্সেস এবং ট্রান্সফার ম্যানেজ করুন",
    "are_you_sure_remove": "আপনি কি নিশ্চিতভাবে এই সদস্যকে সরাতে চান",
    "member_removed": "সদস্য সরানো হয়েছে",
    "join_mess_to_see_members": "সদস্যদের দেখতে মেসে যোগদান করুন।",
    "mess": "মেস",
    "not_set": "সেট করা হয়নি",
    "no_mess": "মেস নেই",
    "join_or_create_mess_to_manage_meals": "মিল ম্যানেজ করতে দয়া করে মেসে যোগদান করুন বা তৈরি করুন।",
    "no_active_month_manager_start": "কোনো সক্রিয় মাস পাওয়া যায়নি। মাস শুরু করতে আপনার ম্যানেজারকে বলুন।",
    "total_meals_month": "মোট মিল (মাস)",
    "my_meals": "আমার মিল",
    "personal_consumption": "ব্যক্তিগত খরচ",
    "active_days": "সক্রিয় দিন",
    "days_with_records": "রেকর্ডসহ দিন",
    "no_meal_records_month": "এই মাসের জন্য কোনো মিল রেকর্ড পাওয়া যায়নি।",
    "daily_total": "দৈনিক মোট",
    "today": "আজ",
    "member": "সদস্য",
    "total_and_actions": "মোট এবং অ্যাকশন",
    "confirm_delete_deposit": "আপনি কি নিশ্চিত যে আপনি এই জমা মুছতে চান?",
    "deposit_deleted": "জমা মুছে ফেলা হয়েছে",
    "confirm_delete_expense": "আপনি কি নিশ্চিত যে আপনি এই খরচ মুছতে চান?",
    "expense_deleted": "খরচ মুছে ফেলা হয়েছে",
    "split_with_shoppers": "শপারদের সাথে ভাগ করা",
    "paid_by_shopper_required": "পরিশোধকারী (শপার) প্রয়োজন",
    "insufficient_mess_balance": "অপর্যাপ্ত মেস ব্যালেন্স",
    "total_expenses": "মোট খরচ",
    "total_deposits": "মোট জমা",
    "expenses": "খরচ",
    "deposits": "জমা",
    "no_records": "কোনো রেকর্ড পাওয়া যায়নি",
    "loading": "লোড হচ্ছে...",
    "saving": "সংরক্ষণ হচ্ছে...",
    "save_record": "রেকর্ড সংরক্ষণ করুন",
    "save_meal_cost": "বাজার খরচ সংরক্ষণ করুন",
    "save_shared_cost": "শেয়ার্ড খরচ সংরক্ষণ করুন",
    "save_individual_cost": "ব্যক্তিগত খরচ সংরক্ষণ করুন",
    "confirm_deposit": "জমা নিশ্চিত করুন",
    "start_month_btn": "মাস শুরু করুন",
    "processing": "প্রক্রিয়াধীন..."
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
